apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-issuer-controller
  namespace: cert-manager
  labels:
    control-plane: http-issuer-controller
spec:
  selector:
    matchLabels:
      control-plane: http-issuer-controller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: http-issuer-controller
      labels:
        control-plane: http-issuer-controller
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - image: localhost/http-issuer-controller:v0.0.1
        imagePullPolicy: Never
        name: http-issuer-controller
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: http-issuer-controller
      terminationGracePeriodSeconds: 10
