name: Dependabot Auto-Approve PR

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout (actions/checkout)
        uses: actions/checkout@v5

      - name: Check if all checks passed
        run: |
          # Wait 30 minutes for checks completion before checking their final status
          for i in $(seq 1 60); do
            gh pr checks "${{ github.event.pull_request.number }}" --json name,state --jq '.[] | select(.name != "auto-approve") | join(" => ")' > checks_status.txt
            if [ ! -s checks_status.txt ] || grep -q "IN_PROGRESS\|QUEUED" checks_status.txt; then
              echo "Some checks are still in progress. Waiting... (loop $i)"
              sleep 30
            else
              break
            fi
          done
          echo "Final checks status:"
          cat checks_status.txt
          if grep -q "FAILURE\|IN_PROGRESS\|QUEUED" checks_status.txt; then
            echo "Some checks have not passed or were not completed (timeout)."
            exit 1
          fi

      - name: Approve Dependabot PR
        if: success()
        run: |
          gh pr review "${{ github.event.pull_request.number }}" --approve
